### PR TITLE
Optimization of the module

### PR DESCRIPTION
**Pull request by morpheus-87**
Thanks for your great module! In this PR, I optimized it a bit:
1. I fixed the link to the dependency checker in the README
2. I beautified your code a little bit
3. I replaced the deprecated `lodash.compose` with `lodash.flowright`
4. I modified the way of escaping the parameters (it caused problems for me, if I want to reuse the parameters for a second formatting step)
5. I updated the dependencies for testing the code (the test cases still work properly)

What do you think about these changes?

### CODE REVIEW

**Comment by eush77** [comment]
I think that's great. Thanks!

And thank you for the kind words!

> I modified the way of escaping the parameters (it caused problems for me, if I want to reuse the parameters for a second formatting step)

Could you also add a test for this?

**Comment by morpheus-87** [comment]
With the last commit, I added a simple test, that checks, if the parameters are manipulated, when calling the regex-format function. Is that ok like this, @eush77?

**Comment by morpheus-87** [comment]
Is everything done for merging my changes, @eush77?

**Comment by eush77** [comment]
@morpheus-87 Yeah, I'm so sorry it took so long.
Thank you very much!

**Comment by morpheus-87** [comment]
Is it possible to do a release with these changes, @eush77?

**Comment by eush77** [comment]
@morpheus-87  Oh yeah. Sorry! Totally forgot.
Released in 0.3.1.

**Comment by morpheus-87** [comment]
Thank you very much for that, @eush77!

**Pull request merged**
